language: android
jdk: openjdk7
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
    - addon
    - sys-img-armeabi-v7a-android-19
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a -s "480x800"
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedAndroidTest
  - cat app/build/reports/androidTests/connected/*html | awk '/<pre>/ { on=1 } /<\/pre>/ { on = 0 } { if(on) print }'
