name: Build & Test

on:
  push:
    branches:
      - dev
      - play-publisher
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Java Development Kit 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build APK & Run small tests
      run: android/build.sh build
    - name: Run medium & large tests
      uses: ReactiveCircus/android-emulator-runner@v2.2.0
      with:
        api-level: 28
        script: android/build.sh large-tests
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: android/uhabits-android/build/outputs/
